### ISSUE TITLE
Gli abitanti non corrispondono ai Paesi nel branch `corr_vaccini_decessi`

### ISSUE THREAD

**Issue by apalladi** [apalladi/covid_vaccini_monitoraggio#38]
C'è un problema con gli abitanti.
L'errore può essere riprodotto inserendo
`print(i, p, abitanti[i])`
nella funzione 
`corr_window(tw):`

Meglio creare un dictionary per non avere questo tipo di problema 
`{'Italy':60, 'Germany':83, ...}`

0 Bulgaria 9.043072
1 Romania 11.632334
2 Slovakia 6.896655
3 Croatia 4.081657
4 Poland 0.8960049999999999
5 Latvia 10.724553
6 Slovenia 5.813301999999999
7 Czechia 1.325188
8 Estonia 5.548361
9 Hungary 67.564251
10 Greece 83.900471
11 Austria 10.370747
12 Lithuania 9.634162
13 Cyprus 4.9829039999999996
14 Germany 60.367470999999995
15 Sweden 1.8669339999999999
16 Belgium 2.6898619999999998
17 Netherlands 0.634814
18 France 0.514564
19 Finland 17.173094
20 Italy 37.797
21 Denmark 10.167923
22 Spain 19.127772
23 Malta 5.460726
24 Portugal 2.078723

**Comment by apalladi** [comment]
Questo dovrebbe sistemare il problema

```
def corr_window(tw):

    dec_res=[]
    vacc_res=[]

    for i in range(len(paesi)):
        vacc_res.append(get_vaccine_data(paesi[i], time_window = tw, fully=True))
        dec_res.append(get_deaths(paesi[i], time_window = tw)/abitanti[i])
        #print(paesi[i], abitanti[i])
        
    corr_tw = np.corrcoef(vacc_res, dec_res)[0, 1]

    return corr_tw
```

**Comment by apalladi** [comment]
Inoltre propongo di modificare la funzione `get_vaccine_data` come segue, per evitare problemi derivanti da missing values:

```
def get_vaccine_data(country, time_window=30, fully=False):
    """ Recupera dati sulla frazione di vaccinati medi negli ultimi 30 giorni"""
    df_vacc_country2 = df_global[df_global["location"] == country]
    df_vacc_country = df_vacc_country2.fillna(method='ffill').copy()
    if fully==False:
        vacc_fully = np.array(df_vacc_country["people_vaccinated_per_hundred"][-(time_window+1):-1])
    else:
        vacc_fully = np.array(df_vacc_country["people_fully_vaccinated_per_hundred"][-(time_window+1):-1])
    
    vacc_ultimi_Ngiorni = np.mean(vacc_fully)   
    return vacc_ultimi_Ngiorni
```

**Comment by enricocid** [comment]
Se è corretto allora chiudo. :)

**Comment by LivingDeadCloud** [comment]
Scusa Enrico, sì, era corretto, hai fatto bene a chiudere
