### ISSUE TITLE
Popolazione Totale 05/01/2022

### ISSUE THREAD

**Issue by larry77** [apalladi/covid_vaccini_monitoraggio#51]
Complimenti per il progetto!
Sto guardando i dati grezzi disponibili al link

https://raw.githubusercontent.com/apalladi/covid_vaccini_monitoraggio/main/dati/dati_ISS_complessivi.csv

Se sommo i campi

non_vaccinati     vaccinati_1_dose    vaccinati_completo    vaccinati_booster

per la data 2022-01-05

ottengo un totale di circa 62 milioni, il che è evidentemente un risultato troppo elevato.
Mi chiedo se sto sbagliando qualcosa o ci sono delle sovrapposizioni fra le varie categorie.
Grazie in anticipo per la collaborazione!

**Comment by enricocid** [comment]
Ciao, grazie.

Esatto. "vaccinati completo" include anche "vaccinati_booster"

**Comment by larry77** [comment]
OK, grazie.
Quindi se calcolo

vaccinati completo  - vaccinati booster

Ottengo il numero di persone che hanno solo la doppia dose o il vaccino monodose, corretto?

**Comment by enricocid** [comment]
Esatto! :)

**Comment by larry77** [comment]
Grazie!
Se ti/vi interessa, date un'occhiata qui

https://dataeu.shinyapps.io/covid_italia/

è un progetto che faccio nel tempo libero. Potrebbe valere la pena unire le forze.
