### ISSUE TITLE
covid_vaccini_monitoraggio discrepanza con bollettino ISS

### ISSUE THREAD

**Issue by mrai5011** [apalladi/covid_vaccini_monitoraggio#53]
Buongiorno.

Non vedo corrispondenza tra i dati riportati qui e il bollettino ISS per esempio 26/01 Decessi 80+ vaccinati: Bollettino 1102+70; monitoraggio 1471. Moltissime discrepanze come questa.  Il dato sui booster sembra coincidere.

Sto interpretando male qualche cosa?
Cordiali saluti,

Maurizio Rainisio

**Comment by apalladi** [comment]
Salve,

il repository è nato quando i booster ancora non esistevano. 

Quando la colonna dei booster è stata aggiunta, noi abbiamo mantenuto la stessa definizione che usavamo in precedenza. Ossia i vaccinati sono coloro che hanno completato il ciclo. Per cui rientrano nei vaccinati tutti coloro che hanno ricevuto 2 o più dosi, quindi vengono sommate le colonne del report ISS relative a
- vaccinati da più di 6 mesi
- vaccinati da meno di 6 mesi
- vacicnati booster
