### ISSUE TITLE
Dati Fasce Età in un solo Excel

### ISSUE THREAD

**Issue by larry77** [apalladi/covid_vaccini_monitoraggio#54]
Buongiorno,
Non è veramente un problema quello che segnalo, ma mi chiedo se sia possibile mettere in un solo file excel tutti i risultati delle varie fasce d'età, come avviene per dati_ISS_complessivi.xlsx.
Sarebbe più pratico per chi usa il vostro database!

**Comment by enricocid** [comment]
Ciao, 
Il problema è che ogni file età ha dati epidemiologici e popolazione di riferimento.

Non so quanto sia pratico un unico file excel con 50+ schede.

Una soluzione potrebbe essere: due schede con dati epid e popolazioni e l'uso di header con data ma poi sarebbe scomodo per noi processare i dati/fare iterazioni (e sinceramente non credo che le librerie di python che usiamo per scrivere i file permettano di gestire layout più complessi)...
Questo modo di salvare i dati ci assicura robustezza del codice.

@apalladi tu che ne pensi?

**Comment by mrai5011** [comment]
Mi permetto di intervenire.
Per metterli insieme ho scritto un semplicissimo script. Simile a quello che avrei scritto per attribuire i denominatori in modo corretto se fossero stati uniti in un solo file.
Per il lavoro che sto facendo (verificare l'utilita` del booster e l'impatto del vaccino completo > o < di 120 giorni) srebbe bello avere questi dati. Capisco il problema di consistenza con i dati "vecchi", ma forse si potrebbe risolvere aggiungendo due colonne.

Comunque grazie per l'ottimo lavoro che mi ha gia` permesso di mostrare che (con molti caveat, limitazioni, ecc.) per i giovani non c'e` un vantaggio evidente.

Maurizio Rainisio

![RR_Ricovero ordinario](https://user-images.githubusercontent.com/60935018/151941042-b11ad901-9cd1-408f-aead-9e10a666bf70.png)

**Comment by larry77** [comment]
Ciao,
Non intendevo un file excel con >50 schede (io mi sparo con una cosa
del genere), ma un solo file con 2 schede che raggruppi tutti i
risultati con un indice che dia la data, come suggerisci tu.

On Tue, Feb 01, 2022 at 12:03:13AM -0800, enricocid wrote:
>Ciao,
>Il problema è che ogni file età ha dati epidemiologici e popolazione di riferimento.
>
>Non so quanto sia pratico un unico file excel con 50+ schede.
>
>Una soluzione potrebbe essere: due schede con dati epid e popolazioni e l'uso di header con data ma poi sarebbe scomodo per noi processare i dati/fare iterazioni (e sinceramente non credo che le librerie di python che usiamo per scrivere i file permettano di gestire layout più complessi)...
>Questo modo di salvare i dati ci assicura robustezza del codice.
>
***@***.*** tu che ne pensi?

**Comment by enricocid** [comment]
@mrai5011 si, raggrupparli con uno script non è un problema. Sto lavorando questi giorni per aggiungere le due colonne proprio per fare questi confronti.
@larry77 si, è la soluzione migliore. Proverò ad adottarla nei prossimi giorni  👍🏻

**Comment by larry77** [comment]
Alla peggio, probabilmente anche un tecnoimbranato come me riesce a
mettere insieme qualcosa per fare lo scraping dei dati delle fasce
d'età secondo le sue esigenze, ma credo che ci sia cmq del valore
aggiunto nel formulare un database che sta in un unico file con 2 sole
(al max!) schede. Grazie 1000!

On Tue, Feb 01, 2022 at 01:18:54AM -0800, enricocid wrote:
***@***.*** si, raggrupparli con uno script non è un problema. Sto lavorando questi giorni per aggiungere le due colonne proprio per fare questi confronti.
***@***.*** si, è la soluzione migliore. Proverò ad adottarla nei prossimi giorni  👍🏻

**Comment by larry77** [comment]
Ho una domanda e se servisse posso aprire un altro issue.
Se vedo il file excel "dati_ISS_complessivi.xlsx", sulla tabella "dati epidemiologici", vedo infezioni, ospedalizzazioni, terapia intensiva e decessi per stato vaccinale (sulle colonne). E mi sembra chiaro.
Nella tabella "popolazioni" però non mi raccapezzo più: per esempio vedo di nuovo i "decessi booster", ma il numero non ha senso. E' possibile che i nomi delle colonne siano sbagliati?
Grazie 1000!

**Comment by apalladi** [comment]
Nella tabella "popolazioni" ci sono le popolazioni relative alle diverse categorie, poiché l'ISS calcola le popolazioni a diversi intervalli di tempo per le diverse categorie. Tipicamente la popolazione dei deceduti riportata nel report è più vecchia di 2 settimane rispetto alla popolazione utilizzata per i ricoverati in TI e gli ospedalizzati.
Nella tabella popolazione la colonna "decessi booster" si riferisce alla popolazione utilizzata dall'ISS per calcolare l'incidenze dei deceduti fra coloro che hanno ricevuto la dose booster
