### ISSUE TITLE
Citare i Vostri Dati

### ISSUE THREAD

**Issue by larry77** [apalladi/covid_vaccini_monitoraggio#56]
Ciao,
Questo non è un vero issue, ma voglio essere certo di evitare situazioni spiacevoli in futuro.
Al link

https://dataeu.shinyapps.io/covid_italia/

trovate un'app (di cui metterò online il codice non appena l'avrò ripulito) che nella sezione "focus vaccini" usa molto i dati del vostro repository.
Mi sembra di citarvi ogni volta che serve, ma se avete qualche osservazione da fare (anche sul contenuto!) siete i benvenuti.

**Comment by enricocid** [comment]
Non farti problemi che non ci sono 😬 basta citare con un link le fonti. 👍🏻

L'unico appunto che sento di farti è di cercare di armonizzare le rappresentazioni. Per le serie temporali io userei sempre lo stesso stile di grafici a linee (in alcuni grafici metti solo i markers) 😊
