### ISSUE TITLE
Popolazione non vaccinati

### ISSUE THREAD

**Issue by larry77** [apalladi/covid_vaccini_monitoraggio#63]
Ciao,
Sto guardando il file Excel "dati_ISS_complessivi.xlsx".
Se guardo le popolazioni dei non vaccinati (foglio "popolazioni", colonna B) in data odierna (5 giugno 2022) noto che c'e' un incremento della popolazione dei non vaccinati, un vero e proprio salto, dal 9 al 16 marzo 2022. 
La cosa è impossibile se la definizione di non vaccinati (== zero dosi di vaccino) rimane la stessa.
Sapete se per caso l'ISS ha ricominciato a farci impazzire o sono io che mi sono perso qualcosa?
Grazie 1000 per il lavoro eccellente!

[dati_ISS_complessivi.xlsx](https://github.com/apalladi/covid_vaccini_monitoraggio/files/8839932/dati_ISS_complessivi.xlsx)

**Comment by enricocid** [comment]
Grazie a te :)

Il 16/03 hanno aggiunto la fascia di popolazione 05-11.

![Senza nome](https://user-images.githubusercontent.com/7274841/172056396-cb4fb319-64c2-4d4b-9f58-488bc13d03ad.png)
