### ISSUE TITLE
Grafici con label assi bianche

### ISSUE THREAD

**Issue by LivingDeadCloud** [apalladi/covid_vaccini_monitoraggio#9]
Ho notato che i grafici nella sezione **Risultati** del readme hanno le label degli assi in nero. Questo li rende non leggibili per chi come me utilizza la combinazione di colori scura.
![image](https://user-images.githubusercontent.com/22834605/135044019-155e5792-bf58-4e7a-8be7-85f5447bb201.png)

Credo che la cosa più semplice sarebbe mettere un'immagine dei grafici su sfondo bianco, eliminando così il problema alla radice.

**Comment by apalladi** [comment]
Strano, credevo fosse impostato di default il background bianco. Grazie per la segnalazione, gli darà un'occhiata

**Comment by apalladi** [comment]
@LivingDeadCloud il problema dovrebbe essersi risolto, con l'uso di plt.use.style('default').
Puoi controllare ?

**Comment by LivingDeadCloud** [comment]
Risolto! Chiudo l'issue
